version: '3'
services:
   api-contracts-acts:
      container_name: spring-contract-wiremock
      image: spring-contract-wiremock
      ports:
      - 8080:8080
      - 8082:8082
      environment:
      - CONTRACT_WIREMOCK_PORT=8082